### ISSUE TITLE
Documentation currently not showing

### ISSUE THREAD

**Issue by matbesancon** [simeonschaub/OptionalArgChecks.jl#1]
I'm still not familiar with GH actions so i couldn't point where exactly the problem is coming from, but both stable and dev links are not showing anything
https://simeonschaub.github.io/OptionalArgChecks.jl/stable

**Comment by simeonschaub** [comment]
Yes, I'm currently working on that. Thanks for the hint!

**Comment by simeonschaub** [comment]
It works now!
